In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import normalize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.datasets import load_iris
from sklearn.tree import export_graphviz

import pandas as pd
from pandas import Series
from sklearn import tree
from sklearn import datasets
from IPython.display import Image
import pydotplus
import numpy as np
import csv
import matplotlib.pyplot as plt
import graphviz

In [ ]:
f1Score = {}
precisionScore = {}
recallScore = {}

In [ ]:
df = pd.read_csv('FIFA18.csv',encoding='utf-8',error_bad_lines=False,index_col=0)
print(df.head(5))

In [107]:
# drop 'Team', 'Opponent', '1st Goal', 'Round','Own goals','Own goal Time' column & update df
df = df.drop(columns=['Team', 'Opponent', '1st Goal', 'Round','Own goals','Own goal Time'])
print(df.head(5))

          Goal Scored  Ball Possession %  Attempts  On-Target  Off-Target  \
Date                                                                        
14-06-18            5                 40        13          7           3   
14-06-18            0                 60         6          0           3   
15-06-18            0                 43         8          3           3   
15-06-18            1                 57        14          4           6   
15-06-18            0                 64        13          3           6   

          Blocked  Corners  Offsides  Free Kicks  Saves  Pass Accuracy %  \
Date                                                                       
14-06-18        3        6         3          11      0               78   
14-06-18        3        2         1          25      2               86   
15-06-18        2        0         1           7      3               78   
15-06-18        4        5         1          13      3               86   
15-0

In [ ]:
# data train & test
X = df[['Goal Scored','Ball Possession %','Attempts','On-Target','Off-Target','Blocked','Saves','Pass Accuracy %','Passes','Fouls']]
Y = df[['Man of the Match']]
x_train, x_test, y_train, y_test = train_test_split(X[['Goal Scored','Ball Possession %','Attempts','On-Target','Off-Target','Blocked','Saves','Pass Accuracy %','Passes','Fouls']],Y[['Man of the Match']],test_size=0.2,random_state=37)

In [ ]:
# decision tree
tree = DecisionTreeClassifier(random_state=0)
tree.fit(x_train,y_train)
print('accuracy of training data:', format(tree.score(x_train,y_train)*100),'%')
print('accuracy of testing data:', format(tree.score(x_test,y_test)*100),'%')

In [110]:
# making decission tree with gini

clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=3, min_samples_leaf=5)
clf_gini.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [115]:
# check single data with gini
clf_gini.predict([[2, 51, 12, 5, 4, 3, 1, 87, 484, 16]])

array(['Yes'], dtype=object)

In [116]:
# making decission tree with information gain/entropy

clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,
 max_depth=3, min_samples_leaf=5)
clf_entropy.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [117]:
# check single data with entropy
clf_entropy.predict([[2, 51, 12, 5, 4, 3, 1, 87, 484, 16]])

array(['Yes'], dtype=object)

In [118]:
# predict test data
y_pred_gini = clf_gini.predict(x_test)
y_pred_en = clf_entropy.predict(x_test)
print('gini prediction: ',y_pred_gini,'\n\n')
print('entropy prediction: ',y_pred_en)

gini prediction:  ['No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No'
 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes'] 


entropy prediction:  ['No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No'
 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes']


In [119]:
# accuracy of gini
print("accuracy of test data in gini: ", accuracy_score(y_test,y_pred_gini)*100,"%\n\n" )

# accuracy of entropy
print("Accuracy of test data in entropy: ", accuracy_score(y_test,y_pred_en)*100,"%" )

accuracy of test data in gini:  53.84615384615385 %


Accuracy of test data in entropy:  53.84615384615385 %


In [120]:
# logistic regression
LG = LogisticRegression()
LG.fit(x_train,y_train)
predictions = LG.predict(x_test)
print('accuracy of training data(logistic regression): ', format(LG.score(x_train,y_train)*100),'%')
print('accuracy of test data (logistic regression): ', format(LG.score(x_test,y_test)*100),'%\n\n')
precisionScore['logistic regression'] = format(precision_score(y_test, predictions, average="macro")*100,'.2f')
recallScore['logistic regression'] = format(recall_score(y_test, predictions, average="macro")*100,'.2f')
f1Score['logistic regression'] = format(f1_score(y_test, predictions, average="macro")*100,'.2f')
cm = confusion_matrix(y_test, predictions)
print('confusion_matrix:\n')
print(cm)

accuracy of training data(logistic regression):  75.49019607843137 %
accuracy of test data (logistic regression):  57.692307692307686 %


confusion_matrix:

[[8 8]
 [3 7]]


c:\python\python37\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [121]:
#naive bayes classifier

NB = GaussianNB()
NB.fit(x_train,y_train)
predictions = NB.predict(x_test)
print('accuracy of training data(naive bayes classifier): ', format(NB.score(x_train,y_train)*100), '%')
print('accuracy of test data(naive bayes classifier): ', format(NB.score(x_test,y_test)*100), '%\n\n')
precisionScore['naive'] = format(precision_score(y_test, predictions, average="macro")*100,'.2f')
recallScore['naive'] = format(recall_score(y_test, predictions, average="macro")*100,'.2f')
f1Score['naive'] = format(f1_score(y_test, predictions, average="macro")*100,'.2f')
cm = confusion_matrix(y_test, predictions)
print('confusion_matrix:\n')
print(cm)

accuracy of training data(naive bayes classifier):  73.52941176470588 %
accuracy of test data(naive bayes classifier):  50.0 %


confusion_matrix:

[[ 6 10]
 [ 3  7]]


c:\python\python37\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [122]:
# random forest
RF = RandomForestClassifier(max_depth=500)
RF.fit(x_train,y_train)
predictions = RF.predict(x_test)
print('accuracy of training data( random forest ): ', format(RF.score(x_train,y_train)*100), '%')
print('accuracy of test data( random forest ): ', format(RF.score(x_test,y_test)*100), '%\n\n')
precisionScore['random forest'] = format(precision_score(y_test, predictions, average="macro")*100,'.2f')
recallScore['random forest'] = format(recall_score(y_test, predictions, average="macro")*100,'.2f')
f1Score['random forest'] = format(f1_score(y_test, predictions, average="macro")*100,'.2f')
cm = confusion_matrix(y_test, predictions)
print('confusion_matrix:\n')
print(cm)

accuracy of training data( random forest ):  98.0392156862745 %
accuracy of test data( random forest ):  61.53846153846154 %


confusion_matrix:

[[10  6]
 [ 4  6]]


c:\python\python37\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [123]:
# svm
S = LinearSVC()
S.fit(x_train,y_train)
predictions = S.predict(x_test)
print('accuracy of training data( support vector classifier ): ', format(S.score(x_train,y_train)*100), '%')
print('accuracy of test data( support vector classifier ): ', format(S.score(x_test,y_test)*100), '%\n\n')
precisionScore['support vector classifier'] = format(precision_score(y_test, predictions, average="macro")*100,'.2f')
recallScore['support vector classifier'] = format(recall_score(y_test, predictions, average="macro")*100,'.2f')
f1Score['support vector classifier'] = format(f1_score(y_test, predictions, average="macro")*100,'.2f')
cm = confusion_matrix(y_test, predictions)
print('confusion_matrix:\n')
print(cm)

accuracy of training data( support vector classifier ):  49.01960784313725 %
accuracy of test data( support vector classifier ):  61.53846153846154 %


confusion_matrix:

[[16  0]
 [10  0]]


c:\python\python37\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\python\python37\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\python\python37\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [124]:
print('all score [precisionScore,recallScore,f1Score]:\n\n')
print('precisionScore: ',precisionScore)
print('recallScore: ',recallScore)
print('f1Score: ',f1Score,'\n\n\n')
print('******** thank you **********')

all score [precisionScore,recallScore,f1Score]:


precisionScore:  {'logistic regression': '59.70', 'naive': '53.92', 'random forest': '60.71', 'support vector classifier': '30.77'}
recallScore:  {'logistic regression': '60.00', 'naive': '53.75', 'random forest': '61.25', 'support vector classifier': '50.00'}
f1Score:  {'logistic regression': '57.63', 'naive': '49.93', 'random forest': '60.61', 'support vector classifier': '38.10'} 



******** thank you **********
